// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

@type {import('@docusaurus/plugin-content-docs').SidebarsConfig}

//  */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  
//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Hướng dẫn cơ bản',
      items: [
       // 'intro', // Tài liệu "intro.md" nằm trong thư mục "docs"
       'tutorial-basics/create-account',
        'tutorial-basics/deposit-money',
        'tutorial-basics/payment-guide',
        'tutorial-basics/quick-buy',
        'tutorial-basics/order-management',
        'tutorial-basics/new-customer-offers',
        'tutorial-basics/vip-policy',
        'tutorial-basics/referral-program',
        'tutorial-basics/terms-of-service',
        'tutorial-basics/privacy-policy',
        'tutorial-basics/create-chatgpt-login-code',
        'tutorial-basics/create-netflix-key',
        'tutorial-basics/create-gmail-account',
        'tutorial-basics/enable-2fa-discord',
        'tutorial-basics/link-email-spotify',
        'tutorial-basics/change-country-google',
        'tutorial-basics/check-google-family',
        'tutorial-basics/delete-google-family',
        'tutorial-basics/leave-google-family',
        'tutorial-basics/setup-and-use-product',
        'tutorial-basics/general-warranty-info',
        'tutorial-basics/netflix-spotify-youtube-warranty',
        'tutorial-basics/setup-anydesk',
        'tutorial-basics/setup-teamviewer',
        'tutorial-basics/setup-chrome-remote-desktop',
        'tutorial-basics/transfer-canva-design',
        'tutorial-basics/download-windows-office',
        'tutorial-basics/install-windows-without-usb',
        'tutorial-basics/remove-microsoft-office',
        'tutorial-basics/logout-netflix-tv',
        'tutorial-basics/change-netflix-language',
      ],
    },
    {
      type: 'category',
      label: 'Hướng dẫn nâng cao',
      items: [
        // 'tutorial-extras/manage-docs-versions',
        // 'tutorial-extras/translate-your-site',
        'tutorial-extras/download-offline-spotify',
        'tutorial-extras/transfer-google-drive-data',
        'tutorial-extras/fix-spotify-premium',
        'tutorial-extras/transfer-spotify-account',
        'tutorial-extras/create-itunes-us-account',
        'tutorial-extras/transfer-youtube-playlist',
        'tutorial-extras/transfer-youtube-channel',
        'tutorial-extras/transfer-youtube-subscriptions',
        'tutorial-extras/check-google-region',
      ],
    },
  ],
};
export default sidebars;
